image: "Visual Studio 2017"

build_script:
  - '.\build.cmd'

test: "off"

artifacts:
  - name: nupkg
    path: '.\artifacts\*.nupkg'

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/chakrygin/api/v2/package
    api_key:
      secure: EXtHXH9NieOgD7qVcd668dbI18n7wDROf32KVTqjxw17N0YFLbvKo8zTDZlO3F+d
    skip_symbols: true
    artifact: nupkg
