image: "Visual Studio 2017"

version: '{build}'

build_script:
  - '.\build.cmd'

test: "off"

artifacts:
  - name: nupkg
    path: '.\artifacts\*.nupkg'

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/chakrygin/api/v2/package
    api_key:
      secure: EXtHXH9NieOgD7qVcd668dbI18n7wDROf32KVTqjxw17N0YFLbvKo8zTDZlO3F+d
    skip_symbols: true
    artifact: nupkg

  - provider: NuGet
    api_key:
      secure: /4akJi/dDEl7y0z/T0fjz0/bHt+9eB9lhvp7+JMWVO0VusTXFG6AHA3TFKm2YHon
    skip_symbols: true
    artifact: nupkg
    on:
      branch: master
      APPVEYOR_REPO_TAG: true
